CREATE TABLE IF NOT EXISTS `CLASES` (
'ID' INT(4) NOT NULL, 
'CLASE' TEXT(20), 
'NOMBRE' TEXT(20), 
'STR' TINYINT(3), 
'DEF' TINYINT(3), 
'CON' TINYINT(3), 
'DEX' TINYINT(3),
'LVL' TINYINT(2), 
PRIMARY KEY (`ID`) )